line-markers/config/routes.rb
Rails.application.routes.draw do
  # scraping_html_elements
  get '/scraping_html_elements/new/:id', to: 'scraping_html_elements#new', as: :new_scraping_html_element
  resources :scraping_html_elements

  # scraping_pages
  namespace :scraping_pages do
    post 'htmls/create/:id', to: 'htmls#create', as: :create_htmls
  end
  resources :scraping_pages

  # scraped_codes
  get '/scraped_codes/new/:id', to: 'scraped_codes#new', as: :new_scraped_codes
  resources :scraped_codes, only: [:index, :create, :edit, :show, :update, :destroy]

  # diff_codes
  get '/diff_codes/new_latest/:id', to: 'diff_codes#new_latest', as: :new_diff_codes_latest
  get '/diff_codes/new/:id', to: 'diff_codes#new', as: :new_diff_codes
  resources :diff_codes, only: [:index, :create, :edit, :show, :update, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

line-markers/app/views/layouts/_header.html.erb
<%= link_to 'Scraping Page', scraping_pages_path %> |
<%= link_to 'Scraping Html Element', scraping_html_elements_path %> |
<%= link_to 'Scraped Code', scraped_codes_path %> |
<%= link_to 'Diff Code', diff_codes_path %>

line-markers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LineMarkers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>