line-markers/config/routes.rb
Rails.application.routes.draw do
  # scraping_html_elements
  get '/scraping_html_elements/new/:id', to: 'scraping_html_elements#new', as: :new_scraping_html_element
  resources :scraping_html_elements

  # scraping_pages
  namespace :scraping_pages do
    post 'htmls/create/:id', to: 'htmls#create', as: :create_htmls
  end
  resources :scraping_pages

  # scraped_codes
  get '/scraped_codes/new/:id', to: 'scraped_codes#new', as: :new_scraped_codes
  resources :scraped_codes, only: [:index, :create, :edit, :show, :update, :destroy]

  # diff_codes
  get '/diff_codes/new_latest/:id', to: 'diff_codes#new_latest', as: :new_diff_codes_latest
  get '/diff_codes/new/:id', to: 'diff_codes#new', as: :new_diff_codes
  resources :diff_codes, only: [:index, :create, :edit, :show, :update, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

line-markers/app/models/scraping_html_element.rb
class ScrapingHtmlElement < ApplicationRecord
  belongs_to :scraping_page
  has_many :scraped_codes, dependent: :destroy
end

line-markers/app/controllers/scraping_html_elements_controller.rb
class ScrapingHtmlElementsController < ApplicationController
  before_action :set_scraping_html_element, only: [:show, :edit, :update, :destroy]

  # GET /scraping_html_elements
  # GET /scraping_html_elements.json
  def index
    @scraping_html_elements = ScrapingHtmlElement.all
  end

  # GET /scraping_html_elements/1
  # GET /scraping_html_elements/1.json
  def show
  end

  # GET /scraping_html_elements/new
  def new
    @scraping_page_id = params[:id]
    
    @scraping_html_element = ScrapingHtmlElement.new
    @scraping_html_element.scraping_page_id = @scraping_page_id
  end

  # GET /scraping_html_elements/1/edit
  def edit
  end

  # POST /scraping_html_elements
  # POST /scraping_html_elements.json
  def create
    @scraping_html_element = ScrapingHtmlElement.new(scraping_html_element_params)

    respond_to do |format|
      if @scraping_html_element.save
        format.html { redirect_to @scraping_html_element, notice: 'Scraping html element was successfully created.' }
        format.json { render :show, status: :created, location: @scraping_html_element }
      else
        format.html { render :new }
        format.json { render json: @scraping_html_element.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scraping_html_elements/1
  # PATCH/PUT /scraping_html_elements/1.json
  def update
    respond_to do |format|
      if @scraping_html_element.update(scraping_html_element_params)
        format.html { redirect_to @scraping_html_element, notice: 'Scraping html element was successfully updated.' }
        format.json { render :show, status: :ok, location: @scraping_html_element }
      else
        format.html { render :edit }
        format.json { render json: @scraping_html_element.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scraping_html_elements/1
  # DELETE /scraping_html_elements/1.json
  def destroy
    @scraping_html_element.destroy
    respond_to do |format|
      format.html { redirect_to scraping_html_elements_url, notice: 'Scraping html element was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scraping_html_element
      @scraping_html_element = ScrapingHtmlElement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scraping_html_element_params
      params.require(:scraping_html_element).permit(:target_element, :scraping_page_id)
    end
end

line-markers/app/helpers/scraping_html_elements_helper.rb
module ScrapingHtmlElementsHelper
end

line-markers/app/views/scraping_html_elements/_form.html.erb
<%= form_with(model: scraping_html_element, local: true) do |form| %>
  <% if scraping_html_element.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scraping_html_element.errors.count, "error") %> prohibited this scraping_html_element from being saved:</h2>

      <ul>
      <% scraping_html_element.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :target_element %>
    <%= form.text_field :target_element %>
  </div>

  <div class="field">
    <%= form.label :scraping_page_id %>
    <%= form.text_field :scraping_page_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

line-markers/app/views/scraping_html_elements/edit.html.erb
<h1>Editing Scraping Html Element</h1>

<%= render 'form', scraping_html_element: @scraping_html_element %>

<%= link_to 'Show', @scraping_html_element %> |
<%= link_to 'Back', scraping_html_elements_path %>

line-markers/app/views/scraping_html_elements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scraping Html Elements</h1>

<table>
  <thead>
    <tr>
      <th>Target element</th>
      <th>スクレイピング</th>
      <th>Scraping page</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scraping_html_elements.each do |scraping_html_element| %>
      <tr>
        <td><%= scraping_html_element.target_element %></td>
        <td><%= link_to 'スクレイピング実行',new_scraped_codes_path(scraping_html_element.id) %></td>
        <td><%= scraping_html_element.scraping_page %></td>
        <td><%= link_to 'Show', scraping_html_element %></td>
        <td><%= link_to 'Edit', edit_scraping_html_element_path(scraping_html_element) %></td>
        <td><%= link_to 'Destroy', scraping_html_element, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

line-markers/app/views/scraping_html_elements/new.html.erb
<h1>New Scraping Html Element</h1>

<%= render 'form', scraping_html_element: @scraping_html_element %>

<%= link_to 'Back', scraping_html_elements_path %>

line-markers/app/views/scraping_html_elements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Target element:</strong>
  <%= @scraping_html_element.target_element %>
</p>

<p>
  <strong>Scraping page:</strong>
  <%= @scraping_html_element.scraping_page %>
</p>

<%= link_to 'Edit', edit_scraping_html_element_path(@scraping_html_element) %> |
<%= link_to 'Back', scraping_html_elements_path %>