line-markers/config/routes.rb
Rails.application.routes.draw do
  # scraping_html_elements
  get '/scraping_html_elements/new/:id', to: 'scraping_html_elements#new', as: :new_scraping_html_element
  resources :scraping_html_elements

  # scraping_pages
  namespace :scraping_pages do
    post 'htmls/create/:id', to: 'htmls#create', as: :create_htmls
  end
  resources :scraping_pages

  # scraped_codes
  get '/scraped_codes/new/:id', to: 'scraped_codes#new', as: :new_scraped_codes
  resources :scraped_codes, only: [:index, :create, :edit, :show, :update, :destroy]

  # diff_codes
  get '/diff_codes/new_latest/:id', to: 'diff_codes#new_latest', as: :new_diff_codes_latest
  get '/diff_codes/new/:id', to: 'diff_codes#new', as: :new_diff_codes
  resources :diff_codes, only: [:index, :create, :edit, :show, :update, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

line-markers/app/models/scraping_page.rb
class ScrapingPage < ApplicationRecord
  has_many :scraping_html_elements, dependent: :destroy
end

line-markers/app/controllers/scraping_pages/htmls_controller.rb
class ScrapingPages::HtmlsController < ApplicationController
  include Scrapable
  include FileSavable

  # $ rails g controller ScrapingPages::Htmls create
  def create
    #--- Set page url ---#
    set_scraping_page # private method
    urls = Array.new
    urls[0] = @scraping_page.page_url # Runs multiple HTTP requests in parallel. If only one request, use url[0].

    #--- Set HTTP request ---#
    requests = scraping_pages_html(urls) # concerns/scrapable.rb
    charset = @scraping_page.charset

    # Scraping loop action
    requests.map { |request|
      directory_path = @scraping_page.directory_path
      file_name = get_file_name(@scraping_page.id)
      body = request.response.body

      save_html(directory_path, file_name, body, charset) # concerns/file_savable.rb

      # Save scraping latest date
      @scraping_page.scraping_latest_date = DateTime.now
      @scraping_page.save
    }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scraping_page
      @scraping_page = ScrapingPage.find(params[:id])
    end
end

line-markers/app/controllers/scraping_pages_controller.rb
class ScrapingPagesController < ApplicationController
  include Scrapable

  before_action :set_scraping_page, only: [:show, :edit, :update, :destroy]

  # GET /scraping_pages
  # GET /scraping_pages.json
  def index
    @scraping_pages = ScrapingPage.all
  end

  # GET /scraping_pages/1
  # GET /scraping_pages/1.json
  def show
  end

  # GET /scraping_pages/new
  def new
    @scraping_page = ScrapingPage.new
    @scraping_page.active = true # default checked
  end

  # GET /scraping_pages/1/edit
  def edit
  end

  # POST /scraping_pages
  # POST /scraping_pages.json
  def create
    @scraping_page = ScrapingPage.new(scraping_page_params)

    #--- Set url and new mechanize ---#
    url = @scraping_page.page_url
    uri = URI.parse(url) # ex) https://example.com/ -> set "example.com"
    agent = Mechanize.new
    page = agent.get(url)

    #--- Set title ---#
    title = page.title if page.respond_to?(:title) # For undefiend page.title method error (ex: RSS or missing title meta tag WebSite).
    title = "#{title} #{uri.host}"
    @scraping_page.title = title

    #--- Set charset ---#
    @scraping_page.charset = set_charset(page.body)

    #--- Obey robots.txt ---#
    robotex = Robotex.new "Crawler"
    @scraping_page.is_robots_allowed = robotex.allowed?(url)

    #--- Set scraping HTML file name ---#
    @scraping_page.directory_path = create_directory(url) # concerns/file_savable.rb

    respond_to do |format|
      if @scraping_page.save
        format.html { redirect_to @scraping_page, notice: 'Scraping page was successfully created.' }
        format.json { render :show, status: :created, location: @scraping_page }
      else
        format.html { render :new }
        format.json { render json: @scraping_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scraping_pages/1
  # PATCH/PUT /scraping_pages/1.json
  def update
    respond_to do |format|
      if @scraping_page.update(scraping_page_params)
        format.html { redirect_to @scraping_page, notice: 'Scraping page was successfully updated.' }
        format.json { render :show, status: :ok, location: @scraping_page }
      else
        format.html { render :edit }
        format.json { render json: @scraping_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scraping_pages/1
  # DELETE /scraping_pages/1.json
  def destroy
    @scraping_page.destroy
    respond_to do |format|
      format.html { redirect_to scraping_pages_url, notice: 'Scraping page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scraping_page
      @scraping_page = ScrapingPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scraping_page_params
      params.require(:scraping_page).permit(:page_url, :active, :charset, :is_robots_allowed)
    end
end

line-markers/app/helpers/scraping_pages/htmls_helper.rb
module ScrapingPages::HtmlsHelper
end

line-markers/app/helpers/scraping_pages_helper.rb
module ScrapingPagesHelper
end

line-markers/app/views/scraping_pages/_form.html.erb
<%= form_with(model: scraping_page, local: true) do |form| %>
  <% if scraping_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scraping_page.errors.count, "error") %> prohibited this scraping_page from being saved:</h2>

      <ul>
      <% scraping_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :page_url %>
    <%= form.text_field :page_url %>
  </div>

  <div class="field">
    <%= form.label :scraping_latest_date %>
    <%= form.text_field :scraping_latest_date %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

line-markers/app/views/scraping_pages/edit.html.erb
<h1>Editing Scraping Page</h1>

<%= render 'form', scraping_page: @scraping_page %>

<%= link_to 'Show', @scraping_page %> |
<%= link_to 'Back', scraping_pages_path %>

line-markers/app/views/scraping_pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scraping Pages</h1>

<%= link_to 'New Scraping Page', new_scraping_page_path %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @scraping_pages.each do |scraping_page| %>
      <tr>
        <td class="url" title="<%= scraping_page.title %>"><%= link_to scraping_page.title, scraping_page.page_url, :target => "_blank" %></td>
        <td><%= link_to 'Show', scraping_page %></td>
        <td><%= link_to 'Edit', edit_scraping_page_path(scraping_page) %></td>
        <td><%= link_to 'Destroy', scraping_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'HTML取得', scraping_pages_create_htmls_path(scraping_page), method: :post %></td>
        <td><%= link_to 'スクレイピングルール登録', new_scraping_html_element_path(scraping_page) %></td>
        <td>
          <% scraping_page.scraping_html_elements.each do |scraping_html_element| %>
            <p><%= scraping_html_element.target_element %>: <%= link_to 'スクレイピング実行', new_scraped_codes_path(scraping_html_element.id) %></p>
          <% end %>
        </td>
        <td><%= link_to '最新をDiff', new_diff_codes_latest_path(scraping_page) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

line-markers/app/views/scraping_pages/new.html.erb
<h1>New Scraping Page</h1>

<%= render 'form', scraping_page: @scraping_page %>

<%= link_to 'Back', scraping_pages_path %>

line-markers/app/views/scraping_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @scraping_page.title %>
</p>

<p>
  <strong>Page url:</strong>
  <%= @scraping_page.page_url %>
</p>

<p>
  <strong>Directory path:</strong>
  <%= @scraping_page.directory_path %>
</p>

<p>
  <strong>Scraping latest date:</strong>
  <%= @scraping_page.scraping_latest_date %>
</p>

<p>
  <strong>Charset:</strong>
  <%= @scraping_page.charset %>
</p>

<p>
  <strong>Is robots allowed:</strong>
  <%= @scraping_page.is_robots_allowed %>
</p>

<p>
  <strong>Active:</strong>
  <%= @scraping_page.active %>
</p>

<%= link_to 'Edit', edit_scraping_page_path(@scraping_page) %> |
<%= link_to 'Back', scraping_pages_path %>