line-markers/config/routes.rb
Rails.application.routes.draw do
  # scraping_html_elements
  get '/scraping_html_elements/new/:id', to: 'scraping_html_elements#new', as: :new_scraping_html_element
  resources :scraping_html_elements

  # scraping_pages
  namespace :scraping_pages do
    post 'htmls/create/:id', to: 'htmls#create', as: :create_htmls
  end
  resources :scraping_pages

  # scraped_codes
  get '/scraped_codes/new/:id', to: 'scraped_codes#new', as: :new_scraped_codes
  resources :scraped_codes, only: [:index, :create, :edit, :show, :update, :destroy]

  # diff_codes
  get '/diff_codes/new_latest/:id', to: 'diff_codes#new_latest', as: :new_diff_codes_latest
  get '/diff_codes/new/:id', to: 'diff_codes#new', as: :new_diff_codes
  resources :diff_codes, only: [:index, :create, :edit, :show, :update, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

line-markers/app/models/diff_code.rb
class DiffCode < ApplicationRecord
  belongs_to :scraped_code
end

line-markers/app/controllers/diff_codes_controller.rb
class DiffCodesController < ApplicationController
  include Diffable # concerns/diffable.rb

  before_action :set_diff_code, only: [:show, :edit, :update, :destroy]

  # GET /diff_codes
  # GET /diff_codes.json
  def index
    @diff_codes = DiffCode.all
  end

  # GET /diff_codes/1
  # GET /diff_codes/1.json
  def show
  end

  def new_latest
    @diff_code = DiffCode.new

    scraped_code = ScrapedCode.new.latest_two(params[:id]) # args ScrapingPage.id
    master_code = scraped_code[0]
    previous_code = scraped_code[1]

    no_previous_code(previous_code) # if can't diff, redirect to index

    diff_with_trimming(master_code, previous_code) # Diffable module
  end

  # GET /diff_codes/new
  def new
    @diff_code = DiffCode.new

    master_code = ScrapedCode.find(params[:id])
    previous_code = ScrapedCode.new.previous_record(master_code.id, master_code.scraping_html_element_id, master_code.created_at)

    no_previous_code(previous_code) # if can't diff, redirect to index

    diff_with_trimming(master_code, previous_code) # return: @diff_code. Diffable module
  end


  # GET /diff_codes/1/edit
  def edit
  end

  # POST /diff_codes
  # POST /diff_codes.json
  def create
    @diff_code = DiffCode.new(diff_code_params)

    respond_to do |format|
      if @diff_code.save
        format.html { redirect_to @diff_code, notice: 'Diff code was successfully created.' }
        format.json { render :show, status: :created, location: @diff_code }
      else
        format.html { render :new }
        format.json { render json: @diff_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diff_codes/1
  # PATCH/PUT /diff_codes/1.json
  def update
    respond_to do |format|
      if @diff_code.update(diff_code_params)
        format.html { redirect_to @diff_code, notice: 'Diff code was successfully updated.' }
        format.json { render :show, status: :ok, location: @diff_code }
      else
        format.html { render :edit }
        format.json { render json: @diff_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diff_codes/1
  # DELETE /diff_codes/1.json
  def destroy
    @diff_code.destroy
    respond_to do |format|
      format.html { redirect_to diff_codes_url, notice: 'Diff code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diff_code
      @diff_code = DiffCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diff_code_params
      params.require(:diff_code).permit(:html, :text, :scraped_code_created_at, :scraping_html_element_id, :scraped_code_id)
    end

    def no_previous_code(previous_code)
      if previous_code == nil
        redirect_to :action => 'index', alert: '比較対象がありません。もう１件、スクレイピングデータが追加されれば比較できます。'
      end
    end
end

line-markers/app/helpers/diff_codes_helper.rb
module DiffCodesHelper
end

line-markers/app/views/diff_codes/_form.html.erb
<%= form_with(model: diff_code, local: true) do |form| %>
  <% if diff_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(diff_code.errors.count, "error") %> prohibited this diff_code from being saved:</h2>

      <ul>
      <% diff_code.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :html %>
    <%= form.text_area :html, size: '100x10' %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text, size: '100x10' %>
  </div>

  <div class="field">
    <%= form.label :scraped_code_created_at %>
    <%= form.datetime_select :scraped_code_created_at %>
  </div>

  <div class="field">
    <%= form.label :scraping_html_element_id %>
    <%= form.text_field :scraping_html_element_id %>
  </div>

  <div class="field">
    <%= form.label :scraped_code_id %>
    <%= form.text_field :scraped_code_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

line-markers/app/views/diff_codes/edit.html.erb
<h1>Editing Diff Code</h1>

<%= render 'form', diff_code: @diff_code %>

<%= link_to 'Show', @diff_code %> |
<%= link_to 'Back', diff_codes_path %>

line-markers/app/views/diff_codes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Diff Codes</h1>

<table>
  <thead>
    <tr>
      <th>Scraping Page ID</th>
      <th>Html</th>
      <th>Text</th>
      <th>Scraped code created at</th>
      <th>Scraping page</th>
      <th>Scraped code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @diff_codes.each do |diff_code| %>
      <tr>
        <td><%= diff_code.scraping_html_element_id %></td>
        <td class="code" title="<%= diff_code.html %>"><%= diff_code.html %></td>
        <td class="code" title="<%= diff_code.text %>"><%= diff_code.text %></td>
        <td><%= diff_code.scraped_code_created_at %></td>
        <td><%= diff_code.scraping_html_element_id %></td>
        <td><%= diff_code.scraped_code %></td>
        <td><%= link_to 'Show', diff_code %></td>
        <td><%= link_to 'Edit', edit_diff_code_path(diff_code) %></td>
        <td><%= link_to 'Destroy', diff_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

line-markers/app/views/diff_codes/new.html.erb
<h1>New Diff Code</h1>

<%= render 'form', diff_code: @diff_code %>

<%= link_to 'Back', diff_codes_path %>

line-markers/app/views/diff_codes/new_latest.html.erb
<h1>New Diff Code</h1>

<%= render 'form', diff_code: @diff_code %>

<%= link_to 'Back', diff_codes_path %>

line-markers/app/views/diff_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Html:</strong>
  <%= raw @diff_code.html %>
</p>

<p>
  <strong>Text:</strong>
  <%= raw @diff_code.text %>
</p>

<p>
  <strong>Scraped code created at:</strong>
  <%= @diff_code.scraped_code_created_at %>
</p>

<p>
  <strong>Scraping html element id:</strong>
  <%= @diff_code.scraping_html_element_id %>
</p>

<p>
  <strong>Scraped code:</strong>
  <%= @diff_code.scraped_code %>
</p>

<%= link_to 'Edit', edit_diff_code_path(@diff_code) %> |
<%= link_to 'Back', diff_codes_path %>